### ISSUE TITLE
See https://github.com/capitaomorte/eslack

### ISSUE THREAD

**Issue by joaotavora** [raamdev/slack-el#1]
It's not very featureful, but currently working and hopefully designed in such a way that new features can be added quickly.

**Comment by raamdev** [comment]
@capitaomorte Thanks so much for the heads up! I'm so excited to see Slack working inside Emacs! :-) I tried to get yours running, but ran into some issues. I opened a GitHub issue in your repo: https://github.com/capitaomorte/eslack/issues/1
